---
title: "PIP Innovation Hub"
subtitle: "Information for authors: Submission steps"
author: Global Poverty & Inequality Data (GPID) team
format: 
  html:
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true
    toc-title: CONTENTS
    theme: default
    number-sections: true
editor: visual
---



This document is intended for authors whose work will be featured in the PIP Innovation Hub. Please read the submission requirements below and follow the steps to submit your work.

## About the PIP Innovation Hub {.unnumbered}

The *PIP Innovation Hub*, to be launched at the Annual Meetings of the IMF and the World Bank on 25 October 2024, is intended to be a home for innovative work on poverty measurement. It will showcase new methods for poverty and inequality estimation that tackle some of the biggest measurement challenges. It will form a part of the [Poverty and Inequality Platform (PIP)](pip.worldbank.org), and will illustrate the impact of different methodological decisions by displaying experimental estimates using alternative methods to those currently shown in the PIP. The Hub will showcase these estimates in an interactive dashboard, display the methodological notes, and link to any associated papers to highlight the work further.



<!-- ## About the Innovation Hub -->

<!-- The objective of PIP Innovation Hub is to foster innovation by providing poverty and inequality estimates that use alternative methods to tackle some of the biggest measurement challenges. It will also show the impact of different methodological decisions. -->

<!-- Some of the main criteria for showcased work include: -->

<!-- -   Methods should be "generalizible", that is, that provide global or regional estimates of poverty, or that span a large number of countries (i.e., not country-specific innovations). -->

<!-- -   must describe the issue with current poverty and inequality estimates intended to be addressed; -->

<!-- -   estimates must be tagged to a particular PIP vintage to foster comparability and interoperability with the latest estimates; -->

<!-- -   must be uploaded to the Development Data Hub with metadata and description to guide users; -->

<!-- -   and must be described in a [World Bank Policy Research Working Paper](https://www.worldbank.org/en/research/brief/world-bank-policy-research-working-papers), a [Global Poverty Monitoring Technical Note (GPMTN)](https://ideas.repec.org/s/wbk/wbgpmt.html), or a published paper. -->

## Submission Requirements

Thank you for being part of PIP Innovation Hub!

Authors wishing to showcase their work in PIP Innovation Hub are required to submit three main inputs: 

1) A `.dta` file fulfilling the stated requirements with the global, regional and/or country-level poverty estimates produced from their method; 

2) A `.xlsx` excel file containing metadata information; and 

3) A `.md` file with a brief methodological note. 

The details and specific formats for each component are described below.

### Data file

The data, submitted in a `.dta` format, should contain the columns given in the excerpt below:

```{r echo = FALSE, warning=FALSE, message=FALSE,}
library(fastverse)
dir    <- "P:/04.GPID_team/PIP-innovation-hub/data-test"
dt_pip <- haven::read_dta(fs::path(dir, 
                                   "dt_pip.dta"))
dt_pip |> 
  fselect(code, 
          year, 
          reporting_level, 
          welfare_type, 
          poverty_line, 
          headcount) |> 
  fsubset(year == 2022) |> 
  head()
```

An example, template file can be downloaded [here](https://pip.worldbank.org/home).
The "code" should give the economy code or for regional aggregates it should be the region code, as seen [here](https://data.worldbank.org/country). The "headcount" should be a decimal between 0 and 1 giving the estimated poverty headcount. The poverty line should be in 2017$ PPP terms and there should, preferably, be three poverty lines per economy per year: \$2.15, \$3.65, and \$6.85

The data should also be tagged to a particular PIP vintage to foster comparability and interoperability with the latest estimates. The PIP vintage will be specified in the metadata. 



### Metadata file

The metadata file consists on all relevant information on your paper such as title, description, dates, URLs, indicators and economies included/excluded, etc. This information must be submitted through an excel file, `.xslx`, filling out one single row with 20 columns:

The metadata template, with more detail on each entry, can be found [here](fake link).

### Methodological Note

Finally, authors should provide brief details on the approach in a methodological note, describing the issue with current poverty/inequality estimates it is trying to address. This note should not be longer than 2 paragraphs, and must include official link to paper. The note should be submitted in a `.md` format, and will be made available to all users of the Hub to read when they view the data.

`methodological_note_template.tex`

## Submission Portal

Finally, the three inputs described in the previous section must be submitted through the following portal:

\[URL: \]

###  {.unnumbered}

We thank you for your contributions and participation in PIP Innovation Hub!

-The GPID Team
